!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          VR_offset_transform: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 1
              name: VR_offset_transform
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              vr_pitch_offset: -0.015440897443425274
              vr_roll_offset: 1.5527395976758895
              vr_x_offset: -2.297687065349697
              vr_y_offset: -0.7137690922361619
              vr_yaw_offset: -2.290444734010314
              vr_z_offset: -0.4492226324082542
            state: []
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  vr_pitch_offset: -0.015440897443425274
  vr_roll_offset: 1.5527395976758895
  vr_x_offset: -2.297687065349697
  vr_y_offset: -0.7137690922361619
  vr_yaw_offset: -2.290444734010314
  vr_z_offset: -0.4492226324082542
state: []
