!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          VR_offset_transform: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 1
              name: VR_offset_transform
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              vr_pitch_offset: -0.030378446851209353
              vr_roll_offset: 1.5344190720654152
              vr_x_offset: -1.8680345736951303
              vr_y_offset: -2.5938461539376467
              vr_yaw_offset: -0.6232114122708073
              vr_z_offset: 2.9470147336470465
            state: []
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  vr_pitch_offset: -0.030378446851209353
  vr_roll_offset: 1.5344190720654152
  vr_x_offset: -1.8680345736951303
  vr_y_offset: -2.5938461539376467
  vr_yaw_offset: -0.6232114122708073
  vr_z_offset: 2.9470147336470465
state: []
