!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          VR_offset_transform: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 1
              name: VR_offset_transform
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              vr_pitch_offset: -0.030436468215774858
              vr_roll_offset: 1.5343146132253562
              vr_x_offset: -1.8679761538081228
              vr_y_offset: -2.593748287196668
              vr_yaw_offset: -0.6231810935804643
              vr_z_offset: 2.947388085293291
            state: []
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  vr_pitch_offset: -0.030436468215774858
  vr_roll_offset: 1.5343146132253562
  vr_x_offset: -1.8679761538081228
  vr_y_offset: -2.593748287196668
  vr_yaw_offset: -0.6231810935804643
  vr_z_offset: 2.947388085293291
state: []
